FROM python:3.10-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*
    
COPY environments/preprocessing/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["bash"]